Repository taste-house/mat_zip_front, pull requests merged in 2024-10, with the labels that each got.

#4 feat: Header 생성
  matzip-front/package-lock.json
  matzip-front/package.json
  matzip-front/src/App.vue
  matzip-front/src/asserts/matzip-img.png
  matzip-front/src/component/common/Header/Header.vue
  matzip-front/src/component/common/Header/element/ListMenu.vue
  matzip-front/src/component/common/Header/element/PostMenu.vue
  matzip-front/src/component/common/Header/element/UserMenu.vue
  matzip-front/src/main.js
  package-lock.json
Labels: feat

#5 chore: 로고 파일 추가
  matzip-front/package-lock.json
  matzip-front/src/App.vue
  matzip-front/src/asserts/matzip-logo.png
Labels: chore, rename

#6 chore: 코드 내 파일명 수정
  matzip-front/src/component/common/Header/Header.vue
Labels: chore

#8 refactor: #7 라우터 수정
  matzip-front/src/router/router.js
Labels: refactoring

#10 feat: Review 지도 기능 추가
  matzip-front/index.html
  matzip-front/package-lock.json
  matzip-front/package.json
  matzip-front/src/App.vue
  matzip-front/src/component/review/ReviewMap.vue
  matzip-front/src/views/review/Review.vue
Labels: feat

#12 feat: 게시글 작성 기능 구현
  matzip-front/package-lock.json
  matzip-front/package.json
  matzip-front/src/router/router.js
  matzip-front/src/views/post/PostCreate.vue
Labels: feat

#19 fix: 구현하지 않은 기능 제거
  matzip-front/src/router/router.js
Labels: fix

#15 feat: 로그인, 이메일찾기, 비밀번호 찾기 기능 구현
  matzip-front/package-lock.json
  matzip-front/package.json
  matzip-front/src/assets/matzip-logo.png
  matzip-front/src/component/common/Header/Header.vue
  matzip-front/src/components/auth/Button.vue
  matzip-front/src/components/auth/InputField.vue
  matzip-front/src/components/auth/Modal.vue
  matzip-front/src/components/common/Logo.vue
  matzip-front/src/components/stores/auth.js
  matzip-front/src/main.js
  matzip-front/src/router/router.js
  matzip-front/src/views/auth/FindEmail.vue
  matzip-front/src/views/auth/FindPassword.vue
  matzip-front/src/views/auth/LoginForm.vue
  matzip-front/src/views/auth/ResetPassword.vue
Labels: feat, rename

#20 feat: #13 리스트 전체 조회 기능 구현
  matzip-front/src/component/common/Header/Header.vue
  matzip-front/src/components/lists/ListAllContent.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/Lists/ListAll.vue
Labels: feat

#17 feat: 회원 검색, 활동 등급 관리 (관리자), 간단한 로그인 페이지 구현
  matzip-front/package-lock.json
  matzip-front/src/App.vue
  matzip-front/src/assets/person.png
  matzip-front/src/component/common/Header/Header.vue
  matzip-front/src/components/admin/admin-views/AdminMain.vue
  matzip-front/src/components/admin/admin-views/activity-level/TableComponent.vue
  matzip-front/src/components/admin/admin-views/user-search/SelectComponent.vue
  matzip-front/src/components/admin/admin-views/user-search/UserSearch.vue
  matzip-front/src/components/admin/common/AdminCommonNav.vue
  matzip-front/src/components/admin/common/AdminHeader.vue
  matzip-front/src/components/admin/common/nav/AdminCommonNav.vue
  matzip-front/src/main.js
  matzip-front/src/router/router.js
  matzip-front/src/views/admin/AdminBaseView.vue
  matzip-front/src/views/admin/admin-views/ActivityLevelSearch.vue
  matzip-front/src/views/admin/admin-views/AdminUserSearchView.vue
  matzip-front/src/views/admin/admin-views/UserSearch.vue
  matzip-front/src/views/user/UserBase.vue
  package-lock.json
Labels: feat

#24 feat: #22 메인페이지 기능 구현
  matzip-front/src/components/main/CurrentMap.vue
  matzip-front/src/components/main/HomePost.vue
  matzip-front/src/components/main/HotList.vue
  matzip-front/src/components/main/HotTag.vue
  matzip-front/src/views/home/HomeView.vue
Labels: feat

#18 feat: 회원 상세 조회 기능 구현
  .idea/inspectionProfiles/Project_Default.xml
  matzip-front/src/App.vue
  matzip-front/src/component/common/Header/element/ListMenu.vue
  matzip-front/src/component/common/Header/element/PostMenu.vue
  matzip-front/src/component/common/Header/element/UserMenu.vue
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/userprofile/ElementBox.vue
  matzip-front/src/components/userprofile/FollowerInfo.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/user/UserBase.vue
  matzip-front/src/views/user/UserProfileView.vue
Labels: feat

#25 chore: 백엔드 요청 주소 변경 및 부트스트랩 반응형 좌우 여백 추가
  matzip-front/src/App.vue
  matzip-front/src/components/common/Header/Header.vue
  matzip-front/src/components/common/Header/element/ListMenu.vue
  matzip-front/src/components/common/Header/element/PostMenu.vue
  matzip-front/src/components/common/Header/element/UserMenu.vue
  matzip-front/src/components/review/ReviewMap.vue
  matzip-front/src/views/Lists/ListAll.vue
  matzip-front/src/views/auth/FindEmail.vue
  matzip-front/src/views/auth/FindPassword.vue
  matzip-front/src/views/auth/LoginForm.vue
  matzip-front/src/views/auth/ResetPassword.vue
  matzip-front/src/views/post/PostCreate.vue
  matzip-front/src/views/review/Review.vue
  matzip-front/src/views/user/UserBase.vue
Labels: chore

#27 fix: header 폴더명 충돌 복구
  matzip-front/src/components/common/Header/Header.vue
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/common/header/element/ListMenu.vue
  matzip-front/src/components/common/header/element/PostMenu.vue
  matzip-front/src/components/common/header/element/UserMenu.vue
Labels: fix

#28 fix: header 수정
  matzip-front/src/components/common/header/Header.vue
Labels: fix, chore

#30 chore: 더 이상 사용하지 않는 파일 삭제
  matzip-front/src/components/common/header/element/ListMenu.vue
  matzip-front/src/components/common/header/element/PostMenu.vue
  matzip-front/src/components/common/header/element/UserMenu.vue
Labels: fix, chore

#38 feat: 게시글 조회 및 검색 기능 구현
  matzip-front/src/components/post/BoardCategoryList.vue
  matzip-front/src/components/post/PagingBar.vue
  matzip-front/src/components/post/PostItem.vue
  matzip-front/src/components/post/PostList.vue
  matzip-front/src/components/post/SearchBar.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/post/PostCreate.vue
  matzip-front/src/views/post/PostDetail.vue
  matzip-front/src/views/post/PostEdit.vue
  matzip-front/src/views/post/PostList.vue
Labels: feat, chore

#36 fix: 메인페이지 URL, 라우트 수정 #36
  matzip-front/src/router/router.js
  matzip-front/src/views/home/HomeView.vue
Labels: fix

#39 feat: 회원가입/완료페이지 구현
  matzip-front/src/components/auth/InputField.vue
  matzip-front/src/components/stores/auth.js
  matzip-front/src/router/router.js
  matzip-front/src/views/auth/FindEmail.vue
  matzip-front/src/views/auth/FindPassword.vue
  matzip-front/src/views/auth/LoginForm.vue
  matzip-front/src/views/auth/Register.vue
  matzip-front/src/views/auth/RegisterSuccess.vue
  matzip-front/src/views/auth/RegisterTOS.vue
Labels: feat, chore

#45 feat: 마커 커스텀 및 리뷰 조회 모달 구현
  matzip-front/index.html
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/review/ReviewMap.vue
  matzip-front/src/views/review/Review.vue
Labels: feat

#47 feat: 메인 페이지에 지도 추가
  matzip-front/src/components/main/CurrentMap.vue
  matzip-front/src/views/home/HomeView.vue
Labels: feat

#33 feat: 관리자가 로그인 한 후 마이페이지 누르면 관리자 페이지로 이동
  matzip-front/src/App.vue
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/stores/auth.js
  matzip-front/src/views/user/UserBase.vue
Labels: feat

#43 feat: 회원 상세 조회 페이지 (관리자)
  matzip-front/src/components/stores/auth.js
  matzip-front/src/router/router.js
  matzip-front/src/views/admin/admin-views/UserDetail.vue
Labels: feat

#48 feat. 회원 프로필 상세 조회 페이지
  matzip-front/src/components/userprofile/UserList.vue
  matzip-front/src/components/userprofile/UserProfile.vue
  matzip-front/src/views/user/UserProfileView.vue
Labels: fix, feat, chore

#51 docs: readme 작성
  README.md
Labels: doc

#52 refactoring: 메인화면 및 헤더 수정
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/main/HotList.vue
  matzip-front/src/components/main/HotTag.vue
  matzip-front/src/views/home/HomeView.vue
Labels: refactoring

#50 feat: #49 리스트 서랍 조회 기능
  matzip-front/src/components/lists/ListBoxContent.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/Lists/ListBox.vue
Labels: feat

#58 feat: 게시글 상세조회 기능
  matzip-front/src/components/post/PostDetail.vue
  matzip-front/src/components/post/PostItem.vue
  matzip-front/src/components/post/PostList.vue
  matzip-front/src/views/admin/admin-views/ActivityLevelSearch.vue
  matzip-front/src/views/admin/admin-views/UserSearch.vue
  matzip-front/src/views/post/PostCreate.vue
  matzip-front/src/views/post/PostDetail.vue
  matzip-front/src/views/post/PostList.vue
Labels: feat, chore

#54 feat: 신고 목록 조회 페이지 (관리자)
  matzip-front/src/components/admin/admin-views/Penalty/ReportTable.vue
  matzip-front/src/components/admin/common/AdminCommonNav.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/admin/admin-views/PenaltyDetail.vue
  matzip-front/src/views/admin/admin-views/ReportSearch.vue
Labels: feat

#64 docs: 이미지 파일 업로드
  README.md
  asserts/images/Place.jpeg
  asserts/images/PostDetail.jpeg
  asserts/images/PostView.jpeg
  asserts/images/Review.jpeg
  asserts/images/loged in main.jpeg
  asserts/images/login.jpeg
  asserts/images/main.jpeg
Labels: doc

#56 feat: 리스트 상세 조회 기능 수정
  matzip-front/src/assets/CommentMark.png
  matzip-front/src/assets/LikeMark.png
  matzip-front/src/assets/ListMark.png
  matzip-front/src/assets/ListText.png
  matzip-front/src/components/lists/ListDetailCmt.vue
  matzip-front/src/components/lists/ListDetailContent.vue
  matzip-front/src/components/lists/ListDetailMatzip.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/Lists/ListDetail.vue
Labels: feat

#62 feat: 메인페이지에서 게시판 연결 # 61
  matzip-front/src/components/main/HomePost.vue
  matzip-front/src/views/home/HomeView.vue
Labels: feat

#60 feat: 신고 사유 목록 조회 페이지 구현
  matzip-front/src/components/admin/admin-views/Penalty/ReportReasonTable.vue
  matzip-front/src/components/admin/admin-views/user-search/TableComponent.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/admin/admin-views/PeanltyDetail.vue
  matzip-front/src/views/admin/admin-views/ReportReason.vue
  matzip-front/src/views/admin/admin-views/ReportSearch.vue
  matzip-front/src/views/admin/admin-views/UserDetail.vue
  matzip-front/src/views/user/UserProfileView.vue
Labels: feat

#66 feat: 페널티 정보 목록 조회 페이지 구현
  matzip-front/src/router/router.js
  matzip-front/src/views/Lists/ListBox.vue
  matzip-front/src/views/admin/admin-views/ActivityLevelSearch.vue
  matzip-front/src/views/admin/admin-views/PenaltyDetail.vue
  matzip-front/src/views/admin/admin-views/PenaltySearch.vue
  matzip-front/src/views/admin/admin-views/ReportReason.vue
  matzip-front/src/views/admin/admin-views/ReportSearch.vue
  matzip-front/src/views/admin/admin-views/UserSearch.vue
  matzip-front/src/views/user/UserProfileView.vue
Labels: feat

#70 chore: #69 코드 수정
  matzip-front/src/components/main/HomePost.vue
  matzip-front/src/views/Lists/ListBox.vue
Labels: chore

#68 feat: 게시글 삭제 기능 구현
  matzip-front/src/components/post/PostDetail.vue
  matzip-front/src/views/post/PostDetail.vue
Labels: feat

#72 feat: 헤더에 마이페이지 링크 추가
  matzip-front/src/components/admin/common/AdminCommonNav.vue
  matzip-front/src/components/common/header/Header.vue
Labels: feat

#74 chore: home 화면 css 구축
  matzip-front/src/assets/Space.png
  matzip-front/src/components/main/HomePost.vue
  matzip-front/src/components/main/HotList.vue
  matzip-front/src/components/main/HotTag.vue
  matzip-front/src/views/home/HomeView.vue
Labels: refactoring, chore

#82 docs: 관리자 페이지 gif 등록
  assets/gifs/admin/adminActiveLevelSearch.gif
  assets/gifs/admin/adminLogin.gif
  assets/gifs/admin/adminPenaltySearch.gif
  assets/gifs/admin/adminReportReason.gif
  assets/gifs/admin/adminReportSearch.gif
  assets/gifs/admin/adminUserDetailSearch.gif
  assets/gifs/admin/adminUserSearch.gif
  assets/images/Place.jpeg
  assets/images/PostDetail.jpeg
  assets/images/PostView.jpeg
  assets/images/Review.jpeg
  assets/images/loged in main.jpeg
  assets/images/login.jpeg
  assets/images/main.jpeg
  matzip-front/src/components/admin/common/AdminCommonNav.vue
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/router/router.js
  matzip-front/src/views/admin/admin-views/PenaltyDetail.vue
  matzip-front/src/views/admin/admin-views/PenaltySearch.vue
  matzip-front/src/views/admin/admin-views/ReportReason.vue
  matzip-front/src/views/admin/admin-views/ReportSearch.vue
Labels: fix, doc

#76 fix: #75 listAll css 수정 url 연결
  matzip-front/src/components/lists/ListAllContent.vue
  matzip-front/src/views/Lists/ListAll.vue
Labels: chore

#78 chore: 리스트 상세조회, 리스트 서랍 css 수정 및 링크 연결
  matzip-front/src/components/lists/ListBoxContent.vue
  matzip-front/src/components/lists/ListDetailCmt.vue
  matzip-front/src/components/lists/ListDetailContent.vue
  matzip-front/src/components/lists/ListDetailMatzip.vue
  matzip-front/src/components/main/HotList.vue
  matzip-front/src/views/Lists/ListDetail.vue
Labels: chore

#87 doc: readme 작성 및 gif 업로드
  README.md
  assets/gifs/list/List-Comment.gif
  assets/gifs/list/List-GetMatzip.gif
  assets/gifs/list/List-Lists.gif
  assets/gifs/list/ListAll-ListDetail.gif
  assets/gifs/list/ListCreate.gif
  assets/gifs/main/MainHome-List.gif
  assets/gifs/main/MainHome-ListAll.gif
  assets/gifs/main/MainHome-Post.gif
  assets/gifs/main/MainHome-PostList.gif
  assets/gifs/main/MainHome.gif
Labels: doc

#86 feat: 리뷰 작성 기능 추가 및 기타 수정
  matzip-front/src/components/common/header/Header.vue
  matzip-front/src/components/review/ReviewMap.vue
Labels: refactoring, feat

#88 docs: 회고 수정 및 gif파일 업로드
  README.md
  assets/gifs/review/review_playmap.gif
  assets/gifs/review/review_restaurant_review.gif
  assets/gifs/review/review_review_write.gif
Labels: doc

#89 doc: readme listAll 로 이동하는 gif 수정
  README.md
Labels: fix, doc

#90 fix: userProfile view 관련 코드 수정
  matzip-front/src/components/userprofile/UserList.vue
  matzip-front/src/components/userprofile/UserProfile.vue
  matzip-front/src/views/user/UserProfileView.vue
Labels: fix

#93 feat: 리스트 상세 배경에 맵 추가
  matzip-front/src/components/lists/ListDetailMap.vue
  matzip-front/src/views/Lists/ListDetail.vue
Labels: feat

#95 feat: 게시글 수정 기능 구현
  matzip-front/src/components/post/BoardCategoryList.vue
  matzip-front/src/components/post/PostDetail.vue
  matzip-front/src/components/post/PostForm.vue
  matzip-front/src/components/post/SearchBar.vue
  matzip-front/src/views/post/PostCreate.vue
  matzip-front/src/views/post/PostDetail.vue
  matzip-front/src/views/post/PostEdit.vue
  matzip-front/src/views/post/PostList.vue
Labels: feat, chore

#96 feat: 메인페이지 지도 애니메이션
  matzip-front/src/components/main/CurrentMap.vue
  matzip-front/src/views/home/HomeView.vue
Labels: feat

#97 doc: readme 작성 및 게시판 gif 업로드
  README.md
  assets/gifs/post/CategoryPost.gif
  assets/gifs/post/DeletePost.gif
  assets/gifs/post/EditPost.gif
  assets/gifs/post/RegistComment.gif
  assets/gifs/post/RegistPost.gif
  assets/gifs/post/SearchPost.gif
Labels: doc

#98 docs: 화면 설계서, 리뷰 gif 작성
  README.md
Labels: doc
